/* eslint-disable */
import type { Config } from "tailwindcss";
import { typographyTokens } from "./src/styles/tokens/typography";

const textStyles = typographyTokens.textStyles;

function withTextStyle(key: keyof typeof textStyles) {
  const style = textStyles[key];
  return [
    style.fontSize,
    {
      lineHeight: style.lineHeight,
      fontWeight: String(style.fontWeight),
      letterSpacing: style.letterSpacing,
      textTransform: style.textTransform,
    },
  ];
}

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", "[data-theme='dark']"],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        surface: {
          canvas: "var(--color-surface-canvas)",
          base: "var(--color-surface-base)",
          subtle: "var(--color-surface-subtle)",
          muted: "var(--color-surface-muted)",
          raised: "var(--color-surface-raised)",
          card: "var(--color-surface-card)",
          popover: "var(--color-surface-popover)",
          overlay: "var(--color-surface-overlay)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          muted: "var(--color-text-muted)",
          inverse: "var(--color-text-inverse)",
          brand: "var(--color-text-on-brand)",
          accent: "var(--color-text-on-accent)",
          link: "var(--color-text-link)",
          linkHover: "var(--color-text-link-hover)",
        },
        brand: {
          primary: "var(--color-brand-primary)",
          hover: "var(--color-brand-primary-hover)",
          active: "var(--color-brand-primary-active)",
          subtle: "var(--color-brand-subtle)",
          strong: "var(--color-brand-strong)",
          on: "var(--color-brand-on-primary)",
        },
        border: {
          hairline: "var(--color-border-hairline)",
          subtle: "var(--color-border-subtle)",
          strong: "var(--color-border-strong)",
          focus: "var(--color-border-focus)",
          divider: "var(--color-border-divider)",
        },
        status: {
          success: "var(--color-status-success-fg)",
          "success-bg": "var(--color-status-success-bg)",
          "success-border": "var(--color-status-success-border)",
          warning: "var(--color-status-warning-fg)",
          "warning-bg": "var(--color-status-warning-bg)",
          "warning-border": "var(--color-status-warning-border)",
          danger: "var(--color-status-danger-fg)",
          "danger-bg": "var(--color-status-danger-bg)",
          "danger-border": "var(--color-status-danger-border)",
          info: "var(--color-status-info-fg)",
          "info-bg": "var(--color-status-info-bg)",
          "info-border": "var(--color-status-info-border)",
        },
        action: {
          primary: "var(--color-action-primary-bg)",
          "primary-hover": "var(--color-action-primary-hover)",
          "primary-active": "var(--color-action-primary-active)",
          "primary-fg": "var(--color-action-primary-fg)",
          "primary-focus": "var(--color-action-primary-focus-ring)",
          secondary: "var(--color-action-secondary-bg)",
          "secondary-hover": "var(--color-action-secondary-hover)",
          "secondary-active": "var(--color-action-secondary-active)",
          "secondary-fg": "var(--color-action-secondary-fg)",
          "secondary-border": "var(--color-action-secondary-border)",
          "secondary-border-hover": "var(--color-action-secondary-border-hover)",
          "secondary-focus": "var(--color-action-secondary-focus-ring)",
          ghost: "var(--color-action-ghost-fg)",
          "ghost-hover": "var(--color-action-ghost-hover)",
          "ghost-active": "var(--color-action-ghost-active)",
          "ghost-focus": "var(--color-action-ghost-focus-ring)",
          destructive: "var(--color-action-destructive-bg)",
          "destructive-hover": "var(--color-action-destructive-hover)",
          "destructive-active": "var(--color-action-destructive-active)",
          "destructive-fg": "var(--color-action-destructive-fg)",
          "destructive-focus": "var(--color-action-destructive-focus-ring)",
        },
        control: {
          field: "var(--color-control-field-bg)",
          "field-hover": "var(--color-control-field-hover)",
          "field-disabled": "var(--color-control-field-disabled)",
          "field-fg": "var(--color-control-field-fg)",
          "field-placeholder": "var(--color-control-field-placeholder)",
          "field-border": "var(--color-control-field-border)",
          "field-border-hover": "var(--color-control-field-border-hover)",
          "field-border-active": "var(--color-control-field-border-active)",
          "field-focus": "var(--color-control-field-focus-ring)",
          chip: "var(--color-control-chip-bg)",
          "chip-hover": "var(--color-control-chip-hover)",
          "chip-fg": "var(--color-control-chip-fg)",
          "chip-border": "var(--color-control-chip-border)",
        },
        table: {
          header: "var(--color-table-header-bg)",
          "header-fg": "var(--color-table-header-fg)",
          "header-border": "var(--color-table-header-border)",
          divider: "var(--color-table-row-divider)",
          hover: "var(--color-table-row-hover)",
        },
        overlay: {
          scrim: "var(--color-overlay-scrim)",
          tooltip: "var(--color-overlay-tooltip-bg)",
          "tooltip-fg": "var(--color-overlay-tooltip-fg)",
          toast: "var(--color-overlay-toast-bg)",
          "toast-fg": "var(--color-overlay-toast-fg)",
          "toast-accent": "var(--color-overlay-toast-accent)",
          dialog: "var(--color-overlay-dialog-bg)",
          "dialog-border": "var(--color-overlay-dialog-border)",
        },
      },
      spacing: {
        none: "var(--space-none)",
        "3xs": "var(--space-3xs)",
        "2xs": "var(--space-2xs)",
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        "2xl": "var(--space-2xl)",
        "3xl": "var(--space-3xl)",
        "4xl": "var(--space-4xl)",
        "stack-xs": "var(--space-stack-xs)",
        "stack-sm": "var(--space-stack-sm)",
        "stack-md": "var(--space-stack-md)",
        "stack-lg": "var(--space-stack-lg)",
        "inline-sm": "var(--space-inline-sm)",
        "inline-md": "var(--space-inline-md)",
        "inline-lg": "var(--space-inline-lg)",
        section: "var(--space-section)",
        "container-x": "var(--space-container-x)",
        "container-y": "var(--space-container-y)",
        "touch-compact": "var(--size-touch-compact)",
        "touch-comfortable": "var(--size-touch-comfortable)",
        "touch-relaxed": "var(--size-touch-relaxed)",
        "touch-spacious": "var(--size-touch-spacious)",
        scrollbar: "var(--size-scrollbar)",
        "ripple-max": "var(--size-ripple-max)",
        "bottomsheet-handle": "var(--size-bottomsheet-handle)",
        "bottomsheet-handle-width": "var(--size-bottomsheet-handle-width)",
        "bottomsheet-border": "var(--size-bottomsheet-border)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
        full: "var(--radius-full)",
        scrollbar: "var(--radius-scrollbar)",
        focus: "var(--radius-focus)",
        toast: "var(--radius-toast)",
        "install-prompt": "var(--radius-install-prompt)",
        button: "var(--radius-button)",
        badge: "var(--radius-badge)",
      },
      boxShadow: {
        surface: "var(--shadow-surface)",
        raised: "var(--shadow-raised)",
        overlay: "var(--shadow-overlay)",
        popover: "var(--shadow-popover)",
        focus: "var(--shadow-focus)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)"],
        mono: ["var(--font-family-mono)"],
        numeric: ["var(--font-family-numeric)"],
      },
      fontSize: {
        display: withTextStyle("display"),
        headline: withTextStyle("headline"),
        title: withTextStyle("title"),
        subtitle: withTextStyle("subtitle"),
        body: withTextStyle("body"),
        "body-strong": withTextStyle("bodyStrong"),
        "body-sm": withTextStyle("bodySmall"),
        caption: withTextStyle("caption"),
        label: withTextStyle("label"),
        mono: withTextStyle("mono"),
        badge: "var(--font-size-badge)",
        input: "var(--font-size-input)",
      },
      fontSize: {
        display: withTextStyle("display"),
        headline: withTextStyle("headline"),
        title: withTextStyle("title"),
        subtitle: withTextStyle("subtitle"),
        body: withTextStyle("body"),
        "body-strong": withTextStyle("bodyStrong"),
        "body-sm": withTextStyle("bodySmall"),
        caption: withTextStyle("caption"),
        label: withTextStyle("label"),
        mono: withTextStyle("mono"),
      },
      transitionDuration: {
        micro: "var(--motion-duration-micro)",
        small: "var(--motion-duration-small)",
        medium: "var(--motion-duration-medium)",
        large: "var(--motion-duration-large)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
        emphasized: "var(--motion-easing-emphasized)",
        exit: "var(--motion-easing-exit)",
        accelerate: "var(--motion-easing-accelerate)",
        decelerate: "var(--motion-easing-decelerate)",
      },
      minHeight: {
        "touch-compact": "var(--size-touch-compact)",
        "touch-comfortable": "var(--size-touch-comfortable)",
        "touch-relaxed": "var(--size-touch-relaxed)",
        "touch-spacious": "var(--size-touch-spacious)",
        "screen-dynamic": "var(--vh, 100dvh)",
        scrollbar: "var(--size-scrollbar)",
        "ripple-max": "var(--size-ripple-max)",
        "bottomsheet-handle": "var(--size-bottomsheet-handle)",
        "bottomsheet-handle-width": "var(--size-bottomsheet-handle-width)",
        "bottomsheet-border": "var(--size-bottomsheet-border)",
      },
      height: {
        "touch-compact": "var(--size-touch-compact)",
        "touch-comfortable": "var(--size-touch-comfortable)",
        "touch-relaxed": "var(--size-touch-relaxed)",
        "touch-spacious": "var(--size-touch-spacious)",
        "screen-dynamic": "var(--vh, 100dvh)",
        "screen-small": "100svh",
        "screen-large": "100lvh",
        scrollbar: "var(--size-scrollbar)",
        "ripple-max": "var(--size-ripple-max)",
        "bottomsheet-handle": "var(--size-bottomsheet-handle)",
        "bottomsheet-handle-width": "var(--size-bottomsheet-handle-width)",
        "bottomsheet-border": "var(--size-bottomsheet-border)",
      },
      padding: {
        "safe-top": "env(safe-area-inset-top)",
        "safe-bottom": "env(safe-area-inset-bottom)",
        "safe-left": "env(safe-area-inset-left)",
        "safe-right": "env(safe-area-inset-right)",
      },
      margin: {
        "safe-top": "env(safe-area-inset-top)",
        "safe-bottom": "env(safe-area-inset-bottom)",
        "safe-left": "env(safe-area-inset-left)",
        "safe-right": "env(safe-area-inset-right)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down":
          "accordion-down var(--motion-duration-small) var(--motion-easing-standard)",
        "accordion-up": "accordion-up var(--motion-duration-small) var(--motion-easing-standard)",
      },
    },
  },
  safelist: [
    {
      pattern: /(grid|flex|gap|items|justify)-(.*)/,
    },
  ],
  plugins: [],
} satisfies Config;
