/* eslint-disable no-restricted-syntax */
// ⚡ Pre-calculated Design Tokens
// Generated at build-time for optimal performance
// Do not edit manually - run 'npm run generate-tokens' to regenerate

export type CssVariableMap = Record<string, string>;

export const preCalculatedTokens: Record<'light' | 'dark', CssVariableMap> = {
  "light": {
    "--color-surface-canvas": "#e9ecf4",
    "--color-surface-base": "#fdfdff",
    "--color-surface-subtle": "#f4f6fb",
    "--color-surface-muted": "#dfe3f0",
    "--color-surface-raised": "#fbfcff",
    "--color-surface-card": "#fdfdff",
    "--color-surface-popover": "#fbfcff",
    "--color-surface-overlay": "rgba(15, 18, 32, 0.65)",
    "--color-text-primary": "#0f1724",
    "--color-text-secondary": "#4a5163",
    "--color-text-tertiary": "#676d82",
    "--color-text-muted": "#7d8398",
    "--color-text-inverse": "#f6f7ff",
    "--color-text-on-brand": "#f6f7ff",
    "--color-text-on-accent": "#f6f7ff",
    "--color-text-link": "#8B5CF6",
    "--color-text-link-hover": "#7C3AED",
    "--color-border-hairline": "rgba(15, 23, 36, 0.08)",
    "--color-border-subtle": "rgba(15, 23, 36, 0.15)",
    "--color-border-strong": "rgba(15, 23, 36, 0.3)",
    "--color-border-focus": "#8B5CF6",
    "--color-border-divider": "rgba(15, 23, 36, 0.12)",
    "--color-brand-primary": "#8B5CF6",
    "--color-brand-primary-hover": "#7C3AED",
    "--color-brand-primary-active": "#6D28D9",
    "--color-brand-subtle": "#EDE9FE",
    "--color-brand-strong": "#7C3AED",
    "--color-brand-on-primary": "#ffffff",
    "--color-status-success-fg": "#0d8f62",
    "--color-status-success-bg": "#e8f5ef",
    "--color-status-success-border": "#72cba4",
    "--color-status-warning-fg": "#b26a00",
    "--color-status-warning-bg": "#fff2d9",
    "--color-status-warning-border": "#ffc266",
    "--color-status-danger-fg": "#c13a32",
    "--color-status-danger-bg": "#ffe5e2",
    "--color-status-danger-border": "#f38b83",
    "--color-status-info-fg": "#0d73d6",
    "--color-status-info-bg": "#e5f1ff",
    "--color-status-info-border": "#7cbbff",
    "--color-action-primary-bg": "#8B5CF6",
    "--color-action-primary-hover": "#7C3AED",
    "--color-action-primary-active": "#6D28D9",
    "--color-action-primary-fg": "#ffffff",
    "--color-action-primary-focus": "rgba(139, 92, 246, 0.35)",
    "--color-action-secondary-bg": "#f2f4fb",
    "--color-action-secondary-hover": "#e7eafa",
    "--color-action-secondary-active": "#dfe3f5",
    "--color-action-secondary-fg": "#0f1724",
    "--color-action-secondary-border": "rgba(15, 23, 36, 0.18)",
    "--color-action-secondary-border-hover": "rgba(15, 23, 36, 0.3)",
    "--color-action-secondary-focus": "rgba(139, 92, 246, 0.25)",
    "--color-action-ghost-fg": "#0f1724",
    "--color-action-ghost-hover": "rgba(15, 23, 36, 0.06)",
    "--color-action-ghost-active": "rgba(15, 23, 36, 0.12)",
    "--color-action-ghost-focus": "rgba(139, 92, 246, 0.25)",
    "--color-action-destructive-bg": "#c13a32",
    "--color-action-destructive-hover": "#a42e29",
    "--color-action-destructive-active": "#821f1b",
    "--color-action-destructive-fg": "#fdfdff",
    "--color-action-destructive-focus": "rgba(193, 58, 50, 0.35)",
    "--color-control-field-bg": "#f7f8fd",
    "--color-control-field-hover": "#fbfcff",
    "--color-control-field-disabled": "#eceff6",
    "--color-control-field-fg": "#0f1724",
    "--color-control-field-placeholder": "#676d82",
    "--color-control-field-border": "rgba(15, 23, 36, 0.12)",
    "--color-control-field-border-hover": "rgba(15, 23, 36, 0.22)",
    "--color-control-field-border-active": "#8B5CF6",
    "--color-control-field-focus-ring": "rgba(139, 92, 246, 0.35)",
    "--color-control-chip-bg": "#edf0ff",
    "--color-control-chip-fg": "#0f1724",
    "--color-control-chip-border": "rgba(15, 23, 36, 0.18)",
    "--color-control-chip-hover": "#e1e7ff",
    "--color-table-header-bg": "#edf0fa",
    "--color-table-header-fg": "#4a5163",
    "--color-table-header-border": "rgba(15, 23, 36, 0.12)",
    "--color-table-row-divider": "rgba(15, 23, 36, 0.1)",
    "--color-table-row-hover": "rgba(139, 92, 246, 0.08)",
    "--color-overlay-scrim": "rgba(4, 6, 12, 0.6)",
    "--color-overlay-tooltip-bg": "#0a0e1d",
    "--color-overlay-tooltip-fg": "#f6f7ff",
    "--color-overlay-toast-bg": "#f5f6ff",
    "--color-overlay-toast-fg": "#0f1724",
    "--color-overlay-toast-accent": "#8B5CF6",
    "--color-overlay-dialog-bg": "#f9faff",
    "--color-overlay-dialog-border": "rgba(15, 23, 36, 0.1)",
    "--space-none": "0px",
    "--space-3xs": "0.5rem",
    "--space-2xs": "0.75rem",
    "--space-xs": "1rem",
    "--space-sm": "1.25rem",
    "--space-md": "1.5rem",
    "--space-lg": "2rem",
    "--space-xl": "2.5rem",
    "--space-2xl": "3rem",
    "--space-3xl": "3.5rem",
    "--space-4xl": "4rem",
    "--space-stack-xs": "0.75rem",
    "--space-stack-sm": "1rem",
    "--space-stack-md": "1.25rem",
    "--space-stack-lg": "1.5rem",
    "--space-inline-sm": "0.75rem",
    "--space-inline-md": "1rem",
    "--space-inline-lg": "1.25rem",
    "--space-section": "2.5rem",
    "--space-container-x": "1rem",
    "--space-container-y": "1.25rem",
    "--size-touch-compact": "2.75rem",
    "--size-touch-comfortable": "3rem",
    "--size-touch-relaxed": "3.25rem",
    "--size-touch-spacious": "3.5rem",
    "--size-scrollbar": "8px",
    "--size-ripple-max": "200px",
    "--size-bottomsheet-handle": "5px",
    "--size-bottomsheet-handle-width": "40px",
    "--size-bottomsheet-border": "2px"
  },
  "dark": {
    "--color-surface-canvas": "#0B0F14",
    "--color-surface-base": "#0F1420",
    "--color-surface-subtle": "#141a2b",
    "--color-surface-muted": "#1b2235",
    "--color-surface-raised": "#1a2134",
    "--color-surface-card": "#151d31",
    "--color-surface-popover": "#192238",
    "--color-surface-overlay": "rgba(0, 0, 0, 0.7)",
    "--color-text-primary": "#f5f6ff",
    "--color-text-secondary": "#c2c7da",
    "--color-text-tertiary": "#8d94ad",
    "--color-text-muted": "#6f738b",
    "--color-text-inverse": "#0B0F14",
    "--color-text-on-brand": "#0B0F14",
    "--color-text-on-accent": "#0B0F14",
    "--color-text-link": "#A78BFA",
    "--color-text-link-hover": "#C4B5FD",
    "--color-border-hairline": "rgba(255, 255, 255, 0.08)",
    "--color-border-subtle": "rgba(255, 255, 255, 0.16)",
    "--color-border-strong": "rgba(255, 255, 255, 0.3)",
    "--color-border-focus": "#8B5CF6",
    "--color-border-divider": "rgba(255, 255, 255, 0.12)",
    "--color-brand-primary": "#8B5CF6",
    "--color-brand-primary-hover": "#A78BFA",
    "--color-brand-primary-active": "#7C3AED",
    "--color-brand-subtle": "rgba(139, 92, 246, 0.12)",
    "--color-brand-strong": "#A78BFA",
    "--color-brand-on-primary": "#0B0F14",
    "--color-status-success-fg": "#31d193",
    "--color-status-success-bg": "#0f241c",
    "--color-status-success-border": "#27a971",
    "--color-status-warning-fg": "#ffb74d",
    "--color-status-warning-bg": "#271d0c",
    "--color-status-warning-border": "#f5a936",
    "--color-status-danger-fg": "#ff6b6b",
    "--color-status-danger-bg": "#2b1215",
    "--color-status-danger-border": "#ff8c8c",
    "--color-status-info-fg": "#5aa8ff",
    "--color-status-info-bg": "#0d1c2b",
    "--color-status-info-border": "#7cbbff",
    "--color-action-primary-bg": "#8B5CF6",
    "--color-action-primary-hover": "#A78BFA",
    "--color-action-primary-active": "#7C3AED",
    "--color-action-primary-fg": "#0B0F14",
    "--color-action-primary-focus": "rgba(139, 92, 246, 0.4)",
    "--color-action-secondary-bg": "#1b2336",
    "--color-action-secondary-hover": "#1f2940",
    "--color-action-secondary-active": "#182032",
    "--color-action-secondary-fg": "#f5f6ff",
    "--color-action-secondary-border": "rgba(255, 255, 255, 0.18)",
    "--color-action-secondary-border-hover": "rgba(255, 255, 255, 0.28)",
    "--color-action-secondary-focus": "rgba(139, 92, 246, 0.35)",
    "--color-action-ghost-fg": "#f5f6ff",
    "--color-action-ghost-hover": "rgba(255, 255, 255, 0.08)",
    "--color-action-ghost-active": "rgba(255, 255, 255, 0.16)",
    "--color-action-ghost-focus": "rgba(139, 92, 246, 0.35)",
    "--color-action-destructive-bg": "#ff6b6b",
    "--color-action-destructive-hover": "#ff8c8c",
    "--color-action-destructive-active": "#e05656",
    "--color-action-destructive-fg": "#06080f",
    "--color-action-destructive-focus": "rgba(255, 107, 107, 0.45)",
    "--color-control-field-bg": "#151c2e",
    "--color-control-field-hover": "#1b2336",
    "--color-control-field-disabled": "#111627",
    "--color-control-field-fg": "#f5f6ff",
    "--color-control-field-placeholder": "#8d94ad",
    "--color-control-field-border": "rgba(255, 255, 255, 0.14)",
    "--color-control-field-border-hover": "rgba(255, 255, 255, 0.22)",
    "--color-control-field-border-active": "#8B5CF6",
    "--color-control-field-focus-ring": "rgba(139, 92, 246, 0.4)",
    "--color-control-chip-bg": "#1d2740",
    "--color-control-chip-fg": "#f5f6ff",
    "--color-control-chip-border": "rgba(255, 255, 255, 0.16)",
    "--color-control-chip-hover": "#253152",
    "--color-table-header-bg": "#161f33",
    "--color-table-header-fg": "#c2c7da",
    "--color-table-header-border": "rgba(255, 255, 255, 0.12)",
    "--color-table-row-divider": "rgba(255, 255, 255, 0.1)",
    "--color-table-row-hover": "rgba(139, 92, 246, 0.12)",
    "--color-overlay-scrim": "rgba(0, 0, 0, 0.7)",
    "--color-overlay-tooltip-bg": "#05070f",
    "--color-overlay-tooltip-fg": "#f5f6ff",
    "--color-overlay-toast-bg": "#141b2f",
    "--color-overlay-toast-fg": "#f5f6ff",
    "--color-overlay-toast-accent": "#8B5CF6",
    "--color-overlay-dialog-bg": "#141b2f",
    "--color-overlay-dialog-border": "rgba(255, 255, 255, 0.08)",
    "--space-none": "0px",
    "--space-3xs": "0.5rem",
    "--space-2xs": "0.75rem",
    "--space-xs": "1rem",
    "--space-sm": "1.25rem",
    "--space-md": "1.5rem",
    "--space-lg": "2rem",
    "--space-xl": "2.5rem",
    "--space-2xl": "3rem",
    "--space-3xl": "3.5rem",
    "--space-4xl": "4rem",
    "--space-stack-xs": "0.75rem",
    "--space-stack-sm": "1rem",
    "--space-stack-md": "1.25rem",
    "--space-stack-lg": "1.5rem",
    "--space-inline-sm": "0.75rem",
    "--space-inline-md": "1rem",
    "--space-inline-lg": "1.25rem",
    "--space-section": "2.5rem",
    "--space-container-x": "1rem",
    "--space-container-y": "1.25rem",
    "--size-touch-compact": "2.75rem",
    "--size-touch-comfortable": "3rem",
    "--size-touch-relaxed": "3.25rem",
    "--size-touch-spacious": "3.5rem",
    "--size-scrollbar": "8px",
    "--size-ripple-max": "200px",
    "--size-bottomsheet-handle": "5px",
    "--size-bottomsheet-handle-width": "40px",
    "--size-bottomsheet-border": "2px"
  }
} as const;

// Performance: Pre-calculated tokens eliminate ~4ms runtime calculation per theme switch
// Generated: 2025-12-09T21:50:43.694Z
// Tokens: 117 variables per theme
