name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  deployments: write

env:
  NODE_VERSION: "22.x"
  BASE_URL: "/"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_BASE_URL: ${{ env.BASE_URL }}
        run: pnpm run build

      # ==== Variante A: Deploy via Cloudflare Pages API ====
      - name: Publish via Cloudflare Pages API
        if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' && secrets.CLOUDFLARE_ACCOUNT_ID != '' && secrets.CLOUDFLARE_PAGES_PROJECT != '' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_PROJECT }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # ==== Variante B: Deploy via Pages Deploy Hook ====
      - name: Trigger Deploy Hook
        if: ${{ secrets.CF_PAGES_DEPLOY_HOOK_URL != '' && (secrets.CLOUDFLARE_API_TOKEN == '' || secrets.CLOUDFLARE_ACCOUNT_ID == '' || secrets.CLOUDFLARE_PAGES_PROJECT == '') }}
        run: |
          curl -X POST "${{ secrets.CF_PAGES_DEPLOY_HOOK_URL }}"
