name: Deploy to Cloudflare Pages (production)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "22.x" # falls du 20.x nutzt, hier anpassen
      BUILD_DIR: dist # bei Vite Standard
      CF_PAGES_BRANCH: main # Production-Branch bei Pages
      CF_PAGES_PROJECT: ${{ secrets.CLOUDFLARE_PAGES_PROJECT }} # Projekt-Slug

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy (Pages, production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name ${{ env.CF_PAGES_PROJECT }} --branch ${{ env.CF_PAGES_BRANCH }}
