name: Lighthouse

on:
  pull_request:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Serve build
        run: npx --yes serve -s dist & sleep 2
      - name: Run Lighthouse CI
        run: npx --yes lhci autorun --upload.target=temporary-public-storage
